version: '3'
services:
  mailarchive-db:
    container_name: "mailarchive-db"
    image: "mariadb:lts-jammy"
    environment:
      - MYSQL_DATABASE=mailarchive
      - MYSQL_USER=mailarchive
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      mailarchive-net1:
        ipv4_address: ${SUBNET}.2
    ports:
      - ${SUBNET}.1:3306:3306
    restart: always

  mailarchive-server:
    container_name: "mailarchive-server"
    image: "mailarchive:0.1.0"
    environment:
      - MYSQL_HOSTNAME=${SUBNET}.1
      - MYSQL_DATABASE=mailarchive
      - MYSQL_USER=mailarchive
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
      - PILER_HOSTNAME=${MAILARCHIVE_HOST}:${SERVER_PORT}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - USER_PASSWORD=${USER_PASSWORD}
      - USERNAME=${USERNAME}
      - DOMAIN=${DOMAIN}
      - USER_UID=2
    volumes:
      - ${IMPORT}:/import
    ports:
      - ${SERVER_PORT}:80
    networks:
      mailarchive-net1:
        ipv4_address: ${SUBNET}.3
    restart: always

networks:
  mailarchive-net1:
    ipam:
      driver: default
      config:
       - subnet: ${SUBNET}.0/24
