version: '3'
services:
  mailarchive-server:
    container_name: "${CONTAINER_NAME}"
    image: "mailarchive:0.1.0"
    environment:
      - MYSQL_HOSTNAME=localhost
      - MYSQL_DATABASE=mailarchive
      - MYSQL_USER=mailarchive
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
      - PILER_HOSTNAME=${MAILARCHIVE_HOST}:${SERVER_PORT}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - USER_PASSWORD=${USER_PASSWORD}
      - USERNAME=${USERNAME}
      - DOMAIN=${DOMAIN}
      - USER_UID=2
    volumes:
      - ${IMPORT_SENT}:/import/sent
      - ${IMPORT_RECEIVED}:/import/received
    ports:
      - ${SERVER_PORT}:80