version: '3'
services:
  mailarchive-server:
    hostname: ${CONTAINER_NAME}
    container_name: "${CONTAINER_NAME}"
    image: "mailarchive:master"
    environment:
      - MYSQL_HOSTNAME=127.0.0.1
      - MYSQL_DATABASE=mailarchive
      - MYSQL_USER=mailarchive
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
      - PILER_HOSTNAME=${MAILARCHIVE_HOST}:${SERVER_PORT}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - USER_PASSWORD=${USER_PASSWORD}
      - USERNAME=${USERNAME}
      - DOMAIN=${DOMAIN}
      - USER_UID=2
      - SLEEPTIME=3600
    volumes:
      - ${IMPORT_SENT}:/import/sent
      - ${IMPORT_RECEIVED}:/import/received
    ports:
      - ${SERVER_PORT}:80
    restart: always
    networks:
      mailarchive-net:
        ipv4_address: ${SUBNET}.2

networks:
  mailarchive-net:
    ipam:
      driver: default
      config:
       - subnet: ${SUBNET}.0/24